In [1]:
import sys
sys.path.append('..')

In [2]:
from pathlib import Path

In [9]:
import cv2
import numpy as np
import torch
import torch.nn as nn
from torch.autograd import Variable
from torchvision import models

In [5]:
base = 'mobilenet_v2'
MODEL_FILE = '../merge-weights/classifier-009500.pth'

In [28]:
model = getattr(models, base)(pretrained=True)

In [29]:
if base.startswith('resnet'):
    model.fc = nn.Linear(model.fc.in_features, 2)
elif base.startswith('mobilenet'):
    model.classifier[-1] = nn.Linear(model.classifier[-1].in_features, 2)

In [30]:
model.load_state_dict(torch.load(MODEL_FILE, map_location=lambda s, l: s))
model.eval()

MobileNetV2(
  (features): Sequential(
    (0): ConvBNReLU(
      (0): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU6(inplace=True)
    )
    (1): InvertedResidual(
      (conv): Sequential(
        (0): ConvBNReLU(
          (0): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=32, bias=False)
          (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (1): Conv2d(32, 16, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (2): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (2): InvertedResidual(
      (conv): Sequential(
        (0): ConvBNReLU(
          (0): Conv2d(16, 96, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(96, eps=1e-05, momentum=0.1, affine=Tr

In [48]:
images = [cv2.imread(str(image)) for image in list(Path('/home/cvlab/datasets/amano/cylinder/grid-classifier-merge/bg').glob('*.jpg'))]

In [35]:
images = [cv2.imread(f'crop{i}.jpg') for i in range(9)]

In [49]:
results = list(map(float, map(str.strip, open('results.txt').readlines())))

In [50]:
outputs = []
for image in images:
    image = cv2.resize(image, (224, 224))
    image = np.transpose(image, (2, 0, 1))
    inputs = torch.from_numpy(np.expand_dims(image, 0).astype(np.float32))
    
    output = model(inputs)
    _, preds = torch.max(output, 1)
    outputs.append(preds)

In [51]:
outputs

[tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tenso

In [ ]:
show(img.astype(np.uint8))

In [ ]:
from PIL import Image
from IPython.display import display

def show(ary):
    display(Image.fromarray(ary))